# fly.toml app configuration file generated for dry-star-3333 on 2023-04-27T07:13:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dry-star-3333"
primary_region = "nrt"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  APP_URL = "https://dry-star-3333.fly.dev"
  APP_NAME = "Laravel"
  APP_DEBUG = false
  DB_CONNECTION = "pgsql"
  DB_HOST = "db.qvhpfagheenkicxwxabz.supabase.co"
  DB_PORT = 5432
  DB_DATABASE = "postgres"
  DB_USERNAME = "postgres"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
